name: GitHubプロフィール統計

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日更新
  workflow_dispatch:     # 手動実行可能

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 包括的な統計のため、完全な履歴を取得

      - name: プライベートコントリビューションを含むGitHubステータス生成
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: TsunakawaShunya
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: true
          config_display: large
          
          # プライベートコントリビューションを含める
          base_repositories_hidden: true
          
          # 実績プラグイン
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          
          # コード行数プラグイン
          plugin_lines: yes
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base, repositories
          
          # レビュー追跡
          plugin_reviews: yes
          plugin_reviews_limit: 100  # 最新100件のレビューを追跡
          
          # リポジトリ分析
          plugin_repositories: yes
          repositories_affiliations: owner,collaborator,organization_member
          
          # 詳細なアクティビティ
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          
          # 出力生成
          output_action: commit
          committer_branch: metrics
          committer_message: メトリクスを更新
